"""seed tariffs

Revision ID: 6b2afca66c99
Revises: 771295e3864a
Create Date: 2025-09-22 21:04:51.387864+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b2afca66c99'
down_revision = '771295e3864a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    payment_plans_table = sa.table('payment_plans',
        sa.column('id', sa.Integer),
        sa.column('name', sa.String),
        sa.column('description', sa.String),
        sa.column('price_total', sa.Integer),
        sa.column('months', sa.Integer)
    )
    
    op.bulk_insert(payment_plans_table, [
        {
            'name': 'Моментальный тариф',
            'description': 'Оплата сразу, доступ сразу',
            'price_total': 3799,
            'months': 1
        },
        {
            'name': '6 месяцев',
            'description': 'Рассрочка на 6 месяцев',
            'price_total': 4800,
            'months': 6
        },
        {
            'name': '3 месяца',
            'description': 'Рассрочка на 3 месяца',
            'price_total': 4050,
            'months': 3
        },
        {
            'name': '2 месяца',
            'description': 'Рассрочка на 2 месяца',
            'price_total': 3900,
            'months': 2
        }
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM payment_plans")
    # ### end Alembic commands ###
